name: budiawan_app
version: 1.0.0+1
publish_to: none
description: An app Flutter project for budiawan mobile app portofolio.
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_flavor: ^3.1.3
  flutter_form_builder: ^9.2.1
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^9.1.0
  get: 4.6.6
  get_storage: ^2.1.1
  intl: ^0.18.1
  skeletonizer: ^1.1.1

dev_dependencies:
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - .env
    - lib/assets/fonts/
    - lib/assets/images/
    - lib/assets/svg/

  fonts:
    - family: Lato
      fonts:
        - asset: lib/assets/fonts/Lato-Regular.ttf
        - asset: lib/assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic

  uses-material-design: true
